/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiPublicKioskAttendanceRouteImport } from './routes/api/public/kiosk/attendance'
import { Route as ApiPublicKioskEmbeddingsRouteImport } from './routes/api/public/kiosk/embeddings'
import { Route as ApiPublicKioskSyncRouteImport } from './routes/api/public/kiosk/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskAttendanceRoute =
  ApiPublicKioskAttendanceRouteImport.update({
    id: '/api/public/kiosk/attendance',
    path: '/api/public/kiosk/attendance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKioskEmbeddingsRoute =
  ApiPublicKioskEmbeddingsRouteImport.update({
    id: '/api/public/kiosk/embeddings',
    path: '/api/public/kiosk/embeddings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKioskSyncRoute = ApiPublicKioskSyncRouteImport.update({
  id: '/api/public/kiosk/sync',
  path: '/api/public/kiosk/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/kiosk/attendance': typeof ApiPublicKioskAttendanceRoute
  '/api/public/kiosk/embeddings': typeof ApiPublicKioskEmbeddingsRoute
  '/api/public/kiosk/sync': typeof ApiPublicKioskSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/kiosk/attendance': typeof ApiPublicKioskAttendanceRoute
  '/api/public/kiosk/embeddings': typeof ApiPublicKioskEmbeddingsRoute
  '/api/public/kiosk/sync': typeof ApiPublicKioskSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/public/kiosk/attendance': typeof ApiPublicKioskAttendanceRoute
  '/api/public/kiosk/embeddings': typeof ApiPublicKioskEmbeddingsRoute
  '/api/public/kiosk/sync': typeof ApiPublicKioskSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/public/kiosk/attendance'
    | '/api/public/kiosk/embeddings'
    | '/api/public/kiosk/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/public/kiosk/attendance'
    | '/api/public/kiosk/embeddings'
    | '/api/public/kiosk/sync'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/api/public/kiosk/attendance'
    | '/api/public/kiosk/embeddings'
    | '/api/public/kiosk/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ApiPublicKioskAttendanceRoute: typeof ApiPublicKioskAttendanceRoute
  ApiPublicKioskEmbeddingsRoute: typeof ApiPublicKioskEmbeddingsRoute
  ApiPublicKioskSyncRoute: typeof ApiPublicKioskSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/attendance': {
      id: '/api/public/kiosk/attendance'
      path: '/api/public/kiosk/attendance'
      fullPath: '/api/public/kiosk/attendance'
      preLoaderRoute: typeof ApiPublicKioskAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/embeddings': {
      id: '/api/public/kiosk/embeddings'
      path: '/api/public/kiosk/embeddings'
      fullPath: '/api/public/kiosk/embeddings'
      preLoaderRoute: typeof ApiPublicKioskEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/sync': {
      id: '/api/public/kiosk/sync'
      path: '/api/public/kiosk/sync'
      fullPath: '/api/public/kiosk/sync'
      preLoaderRoute: typeof ApiPublicKioskSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ApiPublicKioskAttendanceRoute: ApiPublicKioskAttendanceRoute,
  ApiPublicKioskEmbeddingsRoute: ApiPublicKioskEmbeddingsRoute,
  ApiPublicKioskSyncRoute: ApiPublicKioskSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
