/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminInstallRouteImport } from './routes/admin/install'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStaffIndexRouteImport } from './routes/admin/staff/index'
import { Route as AdminStaffIdRouteImport } from './routes/admin/staff/$id'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminStudentsIdRouteImport } from './routes/admin/students/$id'
import { Route as ApiPublicAgentFileRouteImport } from './routes/api/public/agent/$file'
import { Route as ApiPublicKioskAttendanceRouteImport } from './routes/api/public/kiosk/attendance'
import { Route as ApiPublicKioskEmbeddingsRouteImport } from './routes/api/public/kiosk/embeddings'
import { Route as ApiPublicKioskSyncRouteImport } from './routes/api/public/kiosk/sync'
import { Route as ApiPublicKioskWebScanRouteImport } from './routes/api/public/kiosk/web-scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInstallRoute = AdminInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffIndexRoute = AdminStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffIdRoute = AdminStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsIdRoute = AdminStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicAgentFileRoute = ApiPublicAgentFileRouteImport.update({
  id: '/api/public/agent/$file',
  path: '/api/public/agent/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskAttendanceRoute =
  ApiPublicKioskAttendanceRouteImport.update({
    id: '/api/public/kiosk/attendance',
    path: '/api/public/kiosk/attendance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKioskEmbeddingsRoute =
  ApiPublicKioskEmbeddingsRouteImport.update({
    id: '/api/public/kiosk/embeddings',
    path: '/api/public/kiosk/embeddings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicKioskSyncRoute = ApiPublicKioskSyncRouteImport.update({
  id: '/api/public/kiosk/sync',
  path: '/api/public/kiosk/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKioskWebScanRoute = ApiPublicKioskWebScanRouteImport.update({
  id: '/api/public/kiosk/web-scan',
  path: '/api/public/kiosk/web-scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/install': typeof AdminInstallRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/api/public/agent/$file': typeof ApiPublicAgentFileRoute
  '/api/public/kiosk/attendance': typeof ApiPublicKioskAttendanceRoute
  '/api/public/kiosk/embeddings': typeof ApiPublicKioskEmbeddingsRoute
  '/api/public/kiosk/sync': typeof ApiPublicKioskSyncRoute
  '/api/public/kiosk/web-scan': typeof ApiPublicKioskWebScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/install': typeof AdminInstallRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/admin/staff': typeof AdminStaffIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/api/public/agent/$file': typeof ApiPublicAgentFileRoute
  '/api/public/kiosk/attendance': typeof ApiPublicKioskAttendanceRoute
  '/api/public/kiosk/embeddings': typeof ApiPublicKioskEmbeddingsRoute
  '/api/public/kiosk/sync': typeof ApiPublicKioskSyncRoute
  '/api/public/kiosk/web-scan': typeof ApiPublicKioskWebScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/install': typeof AdminInstallRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/staff/$id': typeof AdminStaffIdRoute
  '/admin/students/$id': typeof AdminStudentsIdRoute
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/api/public/agent/$file': typeof ApiPublicAgentFileRoute
  '/api/public/kiosk/attendance': typeof ApiPublicKioskAttendanceRoute
  '/api/public/kiosk/embeddings': typeof ApiPublicKioskEmbeddingsRoute
  '/api/public/kiosk/sync': typeof ApiPublicKioskSyncRoute
  '/api/public/kiosk/web-scan': typeof ApiPublicKioskWebScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/kiosk'
    | '/admin/attendance'
    | '/admin/install'
    | '/admin/settings'
    | '/admin/'
    | '/admin/staff/$id'
    | '/admin/students/$id'
    | '/admin/staff/'
    | '/admin/students/'
    | '/api/public/agent/$file'
    | '/api/public/kiosk/attendance'
    | '/api/public/kiosk/embeddings'
    | '/api/public/kiosk/sync'
    | '/api/public/kiosk/web-scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kiosk'
    | '/admin/attendance'
    | '/admin/install'
    | '/admin/settings'
    | '/admin'
    | '/admin/staff/$id'
    | '/admin/students/$id'
    | '/admin/staff'
    | '/admin/students'
    | '/api/public/agent/$file'
    | '/api/public/kiosk/attendance'
    | '/api/public/kiosk/embeddings'
    | '/api/public/kiosk/sync'
    | '/api/public/kiosk/web-scan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/kiosk'
    | '/admin/attendance'
    | '/admin/install'
    | '/admin/settings'
    | '/admin/'
    | '/admin/staff/$id'
    | '/admin/students/$id'
    | '/admin/staff/'
    | '/admin/students/'
    | '/api/public/agent/$file'
    | '/api/public/kiosk/attendance'
    | '/api/public/kiosk/embeddings'
    | '/api/public/kiosk/sync'
    | '/api/public/kiosk/web-scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KioskRoute: typeof KioskRoute
  ApiPublicAgentFileRoute: typeof ApiPublicAgentFileRoute
  ApiPublicKioskAttendanceRoute: typeof ApiPublicKioskAttendanceRoute
  ApiPublicKioskEmbeddingsRoute: typeof ApiPublicKioskEmbeddingsRoute
  ApiPublicKioskSyncRoute: typeof ApiPublicKioskSyncRoute
  ApiPublicKioskWebScanRoute: typeof ApiPublicKioskWebScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/install': {
      id: '/admin/install'
      path: '/install'
      fullPath: '/admin/install'
      preLoaderRoute: typeof AdminInstallRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/': {
      id: '/admin/staff/'
      path: '/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AdminStaffIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/$id': {
      id: '/admin/staff/$id'
      path: '/staff/$id'
      fullPath: '/admin/staff/$id'
      preLoaderRoute: typeof AdminStaffIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students/$id': {
      id: '/admin/students/$id'
      path: '/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AdminStudentsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/agent/$file': {
      id: '/api/public/agent/$file'
      path: '/api/public/agent/$file'
      fullPath: '/api/public/agent/$file'
      preLoaderRoute: typeof ApiPublicAgentFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/attendance': {
      id: '/api/public/kiosk/attendance'
      path: '/api/public/kiosk/attendance'
      fullPath: '/api/public/kiosk/attendance'
      preLoaderRoute: typeof ApiPublicKioskAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/embeddings': {
      id: '/api/public/kiosk/embeddings'
      path: '/api/public/kiosk/embeddings'
      fullPath: '/api/public/kiosk/embeddings'
      preLoaderRoute: typeof ApiPublicKioskEmbeddingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/sync': {
      id: '/api/public/kiosk/sync'
      path: '/api/public/kiosk/sync'
      fullPath: '/api/public/kiosk/sync'
      preLoaderRoute: typeof ApiPublicKioskSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiosk/web-scan': {
      id: '/api/public/kiosk/web-scan'
      path: '/api/public/kiosk/web-scan'
      fullPath: '/api/public/kiosk/web-scan'
      preLoaderRoute: typeof ApiPublicKioskWebScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminInstallRoute: typeof AdminInstallRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStaffIdRoute: typeof AdminStaffIdRoute
  AdminStudentsIdRoute: typeof AdminStudentsIdRoute
  AdminStaffIndexRoute: typeof AdminStaffIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminInstallRoute: AdminInstallRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStaffIdRoute: AdminStaffIdRoute,
  AdminStudentsIdRoute: AdminStudentsIdRoute,
  AdminStaffIndexRoute: AdminStaffIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KioskRoute: KioskRoute,
  ApiPublicAgentFileRoute: ApiPublicAgentFileRoute,
  ApiPublicKioskAttendanceRoute: ApiPublicKioskAttendanceRoute,
  ApiPublicKioskEmbeddingsRoute: ApiPublicKioskEmbeddingsRoute,
  ApiPublicKioskSyncRoute: ApiPublicKioskSyncRoute,
  ApiPublicKioskWebScanRoute: ApiPublicKioskWebScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
